/*! Copyright (C) 2009 Apertus, All Rights Reserved
 *! Author : Apertus Team
-----------------------------------------------------------------------------**
 *!
 *!  This program is free software: you can redistribute it and/or modify
 *!  it under the terms of the GNU General Public License as published by
 *!  the Free Software Foundation, either version 3 of the License, or
 *!  (at your option) any later version.
 *!
 *!  This program is distributed in the hope that it will be useful,
 *!  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *!  GNU General Public License for more details.
 *!
 *!  You should have received a copy of the GNU General Public License
 *!  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *!
-----------------------------------------------------------------------------**/

import java.awt.CardLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;

public class Settings3Layout extends javax.swing.JPanel {

    ElphelVision Parent;

    public Settings3Layout(ElphelVision parent) {
        Parent = parent;

        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void Load() {
        MultiCameraRecordingDelayField.setText(String.valueOf(Parent.Camera.GetMultiCameraRecordingStartDelay()));
        MovieSplitSizeField.setText(String.valueOf(Parent.Camera.GetMovieClipMaxChunkSize()));

        String[] audio_devices = Parent.Utils.SoundRecorder.GetAvailableAudioMixers();
        for (int i = 0; i < audio_devices.length; i++) {
            if (audio_devices[i] != null) {
                AudioDevices.addItem(new KeyValue(i, audio_devices[i]));
            }
        }
    }

    public class KeyValue {

        private int key;
        private String value;

        public KeyValue(int key, String value) {
            this.key = key;
            this.value = value;
        }

        public int getKey() {
            return key;
        }

        public String getValue() {
            return value;
        }

        public String toString() {
            return value;
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        ConfirmationPanel = new javax.swing.JPanel();
        SettingsOKButton = new EButton(Parent);
        SettingsCancelButton = new EButton(Parent);
        NavigationPanel1 = new javax.swing.JPanel();
        SettingsMenu1Button1 = new EButton(Parent);
        SettingsMenu2Button1 = new EButton(Parent);
        GuidesMenuButton1 = new EButton(Parent);
        SettingsMenu3Button = new EButton(Parent);
        PhotoSettingsMenu = new EButton(Parent);
        ePanel1 = new EPanel();
        ePanel2 = new EPanel();
        MulitCameraRecordingDelay = new javax.swing.JLabel();
        AudioDevices = new javax.swing.JComboBox();
        ePanel3 = new EPanel();
        MovieSplitSizeLabel = new javax.swing.JLabel();
        MovieSplitSizeField = new javax.swing.JTextField();
        MovieSplitSizeType = new EButton(Parent);
        ePanel4 = new EPanel();
        MulitCameraRecordingDelay1 = new javax.swing.JLabel();
        MultiCameraRecordingDelayField = new javax.swing.JTextField();
        MulitCameraRecordingDelayType1 = new EButton(Parent);
        ePanel5 = new EPanel();
        MulitCameraRecordingDelay2 = new javax.swing.JLabel();
        AudioFormats = new javax.swing.JComboBox();

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setPreferredSize(new java.awt.Dimension(1024, 600));

        ConfirmationPanel.setBackground(java.awt.Color.black);

        SettingsOKButton.setText("OK");
        SettingsOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsOKButtonActionPerformed(evt);
            }
        });

        SettingsCancelButton.setText("Cancel");
        SettingsCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConfirmationPanelLayout = new javax.swing.GroupLayout(ConfirmationPanel);
        ConfirmationPanel.setLayout(ConfirmationPanelLayout);
        ConfirmationPanelLayout.setHorizontalGroup(
            ConfirmationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmationPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(SettingsOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SettingsCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ConfirmationPanelLayout.setVerticalGroup(
            ConfirmationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(SettingsCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(SettingsOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        NavigationPanel1.setBackground(java.awt.Color.black);

        SettingsMenu1Button1.setText("Settings Tab 1");
        SettingsMenu1Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsMenu1Button1ActionPerformed(evt);
            }
        });

        SettingsMenu2Button1.setText("Settings Tab 2");
        SettingsMenu2Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsMenu2Button1ActionPerformed(evt);
            }
        });

        GuidesMenuButton1.setText("Guides");
        GuidesMenuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuidesMenuButton1ActionPerformed(evt);
            }
        });

        SettingsMenu3Button.setText("Settings Tab 3");
        SettingsMenu3Button.setChecked(true);
        SettingsMenu3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsMenu3ButtonActionPerformed(evt);
            }
        });

        PhotoSettingsMenu.setText("Photo Settings");
        PhotoSettingsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhotoSettingsMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavigationPanel1Layout = new javax.swing.GroupLayout(NavigationPanel1);
        NavigationPanel1.setLayout(NavigationPanel1Layout);
        NavigationPanel1Layout.setHorizontalGroup(
            NavigationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationPanel1Layout.createSequentialGroup()
                .addComponent(SettingsMenu1Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SettingsMenu2Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SettingsMenu3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GuidesMenuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PhotoSettingsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        NavigationPanel1Layout.setVerticalGroup(
            NavigationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(SettingsMenu1Button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(SettingsMenu2Button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(SettingsMenu3Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(GuidesMenuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(PhotoSettingsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ePanel1.setBackground(new java.awt.Color(13, 20, 27));
        ePanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ePanel2.setBackground(new java.awt.Color(39, 39, 41));
        ePanel2.setBorder(null);
        ePanel2.setForeground(new java.awt.Color(80, 80, 80));

        MulitCameraRecordingDelay.setBackground(new java.awt.Color(1, 1, 1));
        MulitCameraRecordingDelay.setFont(new java.awt.Font("DejaVu Sans", 0, 12));
        MulitCameraRecordingDelay.setForeground(new java.awt.Color(255, 255, 255));
        MulitCameraRecordingDelay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MulitCameraRecordingDelay.setText("Audio Devices");
        MulitCameraRecordingDelay.setAlignmentY(0.0F);
        MulitCameraRecordingDelay.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        MulitCameraRecordingDelay.setIconTextGap(0);
        MulitCameraRecordingDelay.setInheritsPopupMenu(false);
        MulitCameraRecordingDelay.setRequestFocusEnabled(false);
        MulitCameraRecordingDelay.setVerifyInputWhenFocusTarget(false);
        MulitCameraRecordingDelay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        AudioDevices.setFont(new java.awt.Font("DejaVu Sans", 0, 8));
        AudioDevices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AudioDevicesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ePanel2Layout = new javax.swing.GroupLayout(ePanel2);
        ePanel2.setLayout(ePanel2Layout);
        ePanel2Layout.setHorizontalGroup(
            ePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MulitCameraRecordingDelay)
                .addGap(18, 18, 18)
                .addComponent(AudioDevices, 0, 351, Short.MAX_VALUE)
                .addContainerGap())
        );
        ePanel2Layout.setVerticalGroup(
            ePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AudioDevices, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(ePanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(MulitCameraRecordingDelay)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        ePanel1.add(ePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 480, 60));

        ePanel3.setBackground(new java.awt.Color(39, 39, 41));
        ePanel3.setBorder(null);
        ePanel3.setForeground(new java.awt.Color(80, 80, 80));

        MovieSplitSizeLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 12));
        MovieSplitSizeLabel.setForeground(new java.awt.Color(255, 255, 255));
        MovieSplitSizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MovieSplitSizeLabel.setText("Movie Split Size [MB]");
        MovieSplitSizeLabel.setAlignmentY(0.0F);
        MovieSplitSizeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        MovieSplitSizeLabel.setIconTextGap(0);
        MovieSplitSizeLabel.setInheritsPopupMenu(false);
        MovieSplitSizeLabel.setRequestFocusEnabled(false);
        MovieSplitSizeLabel.setVerifyInputWhenFocusTarget(false);
        MovieSplitSizeLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        MovieSplitSizeField.setBackground(new java.awt.Color(0, 0, 0));
        MovieSplitSizeField.setForeground(new java.awt.Color(255, 255, 255));
        MovieSplitSizeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MovieSplitSizeField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        MovieSplitSizeField.setCaretColor(new java.awt.Color(254, 254, 254));
        MovieSplitSizeField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                MovieSplitSizeFieldCaretUpdate(evt);
            }
        });

        MovieSplitSizeType.setText("type");
        MovieSplitSizeType.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        MovieSplitSizeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieSplitSizeTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ePanel3Layout = new javax.swing.GroupLayout(ePanel3);
        ePanel3.setLayout(ePanel3Layout);
        ePanel3Layout.setHorizontalGroup(
            ePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ePanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MovieSplitSizeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(MovieSplitSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MovieSplitSizeType, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ePanel3Layout.setVerticalGroup(
            ePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ePanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MovieSplitSizeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MovieSplitSizeType, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addComponent(MovieSplitSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83))
        );

        ePanel1.add(ePanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 480, 60));

        ePanel4.setBackground(new java.awt.Color(39, 39, 41));
        ePanel4.setBorder(null);
        ePanel4.setForeground(new java.awt.Color(80, 80, 80));

        MulitCameraRecordingDelay1.setBackground(new java.awt.Color(1, 1, 1));
        MulitCameraRecordingDelay1.setFont(new java.awt.Font("DejaVu Sans", 0, 12));
        MulitCameraRecordingDelay1.setForeground(new java.awt.Color(255, 255, 255));
        MulitCameraRecordingDelay1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MulitCameraRecordingDelay1.setText("Multi Camera Recording Delay [seconds]");
        MulitCameraRecordingDelay1.setAlignmentY(0.0F);
        MulitCameraRecordingDelay1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        MulitCameraRecordingDelay1.setIconTextGap(0);
        MulitCameraRecordingDelay1.setInheritsPopupMenu(false);
        MulitCameraRecordingDelay1.setRequestFocusEnabled(false);
        MulitCameraRecordingDelay1.setVerifyInputWhenFocusTarget(false);
        MulitCameraRecordingDelay1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        MultiCameraRecordingDelayField.setBackground(new java.awt.Color(0, 0, 0));
        MultiCameraRecordingDelayField.setForeground(new java.awt.Color(255, 255, 255));
        MultiCameraRecordingDelayField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MultiCameraRecordingDelayField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        MultiCameraRecordingDelayField.setCaretColor(new java.awt.Color(254, 254, 254));
        MultiCameraRecordingDelayField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                MultiCameraRecordingDelayFieldCaretUpdate(evt);
            }
        });

        MulitCameraRecordingDelayType1.setText("type");
        MulitCameraRecordingDelayType1.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        MulitCameraRecordingDelayType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MulitCameraRecordingDelayType1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ePanel4Layout = new javax.swing.GroupLayout(ePanel4);
        ePanel4.setLayout(ePanel4Layout);
        ePanel4Layout.setHorizontalGroup(
            ePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ePanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MulitCameraRecordingDelay1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(MultiCameraRecordingDelayField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MulitCameraRecordingDelayType1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ePanel4Layout.setVerticalGroup(
            ePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ePanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MulitCameraRecordingDelay1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MulitCameraRecordingDelayType1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(MultiCameraRecordingDelayField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        ePanel1.add(ePanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 60));

        ePanel5.setBackground(new java.awt.Color(39, 39, 41));
        ePanel5.setBorder(null);
        ePanel5.setForeground(new java.awt.Color(80, 80, 80));

        MulitCameraRecordingDelay2.setBackground(new java.awt.Color(1, 1, 1));
        MulitCameraRecordingDelay2.setFont(new java.awt.Font("DejaVu Sans", 0, 12));
        MulitCameraRecordingDelay2.setForeground(new java.awt.Color(255, 255, 255));
        MulitCameraRecordingDelay2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MulitCameraRecordingDelay2.setText("Audio Recording Formats");
        MulitCameraRecordingDelay2.setAlignmentY(0.0F);
        MulitCameraRecordingDelay2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        MulitCameraRecordingDelay2.setIconTextGap(0);
        MulitCameraRecordingDelay2.setInheritsPopupMenu(false);
        MulitCameraRecordingDelay2.setRequestFocusEnabled(false);
        MulitCameraRecordingDelay2.setVerifyInputWhenFocusTarget(false);
        MulitCameraRecordingDelay2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        AudioFormats.setFont(new java.awt.Font("DejaVu Sans", 0, 8));

        javax.swing.GroupLayout ePanel5Layout = new javax.swing.GroupLayout(ePanel5);
        ePanel5.setLayout(ePanel5Layout);
        ePanel5Layout.setHorizontalGroup(
            ePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ePanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MulitCameraRecordingDelay2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AudioFormats, 0, 287, Short.MAX_VALUE)
                .addContainerGap())
        );
        ePanel5Layout.setVerticalGroup(
            ePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ePanel5Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(ePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MulitCameraRecordingDelay2)
                    .addComponent(AudioFormats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ePanel1.add(ePanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 480, -1));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(NavigationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                        .addComponent(ConfirmationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NavigationPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmationPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SettingsOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsOKButtonActionPerformed
        Parent.Camera.SetMovieClipMaxChunkSize(Integer.parseInt(MovieSplitSizeField.getText()));
        Parent.Camera.SetMultiCameraRecordingStartDelay(Float.parseFloat(MultiCameraRecordingDelayField.getText()));

        // testing audio recording
        Parent.Utils.SoundRecorder.SetFilename("test.wav");
        int AudioDeviceObjectKey = ((KeyValue) (AudioDevices.getSelectedObjects()[0])).getKey();
        int AudioFormatObjectKey = ((KeyValue) (AudioFormats.getSelectedObjects()[0])).getKey();
        Parent.Utils.SoundRecorder.SetAudioOptions(AudioDeviceObjectKey, AudioFormatObjectKey);

        try { // Save to config file
            Parent.Camera.WriteConfigFile("autosave.config");
        } catch (IOException ex) {
            Logger.getLogger(Settings1Layout.class.getName()).log(Level.SEVERE, null, ex);
        }

        Parent.Utils.SoundRecorder.StartMonitor();

        Parent.LoadMainCard();
    }//GEN-LAST:event_SettingsOKButtonActionPerformed

    private void SettingsCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsCancelButtonActionPerformed
        Parent.StopVideoPlayer();
        Parent.LoadMainCard();
    }//GEN-LAST:event_SettingsCancelButtonActionPerformed

    private void SettingsMenu1Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsMenu1Button1ActionPerformed
        CardLayout cl = (CardLayout) (Parent.GetCardManager().getLayout());
        cl.show(Parent.GetCardManager(), "Settings1Card");
        Parent.StopVideoPlayer();
}//GEN-LAST:event_SettingsMenu1Button1ActionPerformed

    private void SettingsMenu2Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsMenu2Button1ActionPerformed
        CardLayout cl = (CardLayout) (Parent.GetCardManager().getLayout());
        cl.show(Parent.GetCardManager(), "Settings2Card");
        Parent.Settings2CardLayout.Load();
}//GEN-LAST:event_SettingsMenu2Button1ActionPerformed

    private void GuidesMenuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuidesMenuButton1ActionPerformed
        CardLayout cl = (CardLayout) (Parent.GetCardManager().getLayout());
        cl.show(Parent.GetCardManager(), "GuidesCard");
        Parent.GuidesPanel.Load();
}//GEN-LAST:event_GuidesMenuButton1ActionPerformed

    private void SettingsMenu3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsMenu3ButtonActionPerformed
}//GEN-LAST:event_SettingsMenu3ButtonActionPerformed

    private void PhotoSettingsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhotoSettingsMenuActionPerformed
        Parent.PhotoSettingsCardLayout.Load();
        CardLayout cl = (CardLayout) (Parent.GetCardManager().getLayout());
        cl.show(Parent.GetCardManager(), "PhotoSettings");
}//GEN-LAST:event_PhotoSettingsMenuActionPerformed

    private void MovieSplitSizeFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_MovieSplitSizeFieldCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_MovieSplitSizeFieldCaretUpdate

    private void MovieSplitSizeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieSplitSizeTypeActionPerformed
        Parent.NumberPanelInteger.Load("Movie Split Size [MB]", Integer.parseInt(MovieSplitSizeField.getText()), MovieSplitSizeField, "Settings3Card");
        CardLayout cl = (CardLayout) (Parent.GetCardManager().getLayout());
        cl.show(Parent.GetCardManager(), "NumberpanelInteger");
    }//GEN-LAST:event_MovieSplitSizeTypeActionPerformed

    private void MultiCameraRecordingDelayFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_MultiCameraRecordingDelayFieldCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_MultiCameraRecordingDelayFieldCaretUpdate

    private void MulitCameraRecordingDelayType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MulitCameraRecordingDelayType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MulitCameraRecordingDelayType1ActionPerformed

    private void AudioDevicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AudioDevicesActionPerformed
        AudioFormats.removeAllItems();
        KeyValue AudioDeviceObject = (KeyValue) (AudioDevices.getSelectedObjects()[0]);
        AudioFormat[] audio_formats = Parent.Utils.SoundRecorder.GetMixerCapabilities(AudioDeviceObject.getKey());
        if (audio_formats != null) {
            for (int i = 0; i < audio_formats.length; i++) {
                String line = "";
                if (audio_formats[i].getSampleRate() == -1) {
                    line += "Samplerate: any";
                } else {
                    line += "Samplerate: " + audio_formats[i].getSampleRate();
                }
                line += " | Bits: " + audio_formats[i].getSampleSizeInBits();
                line += " | Channels: " + audio_formats[i].getChannels();
                KeyValue entry = new KeyValue(i, line);
                AudioFormats.addItem(entry);
            }
        }
    }//GEN-LAST:event_AudioDevicesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AudioDevices;
    private javax.swing.JComboBox AudioFormats;
    private javax.swing.JPanel ConfirmationPanel;
    private EButton GuidesMenuButton1;
    private javax.swing.JTextField MovieSplitSizeField;
    private javax.swing.JLabel MovieSplitSizeLabel;
    private EButton MovieSplitSizeType;
    private javax.swing.JLabel MulitCameraRecordingDelay;
    private javax.swing.JLabel MulitCameraRecordingDelay1;
    private javax.swing.JLabel MulitCameraRecordingDelay2;
    private EButton MulitCameraRecordingDelayType1;
    private javax.swing.JTextField MultiCameraRecordingDelayField;
    private javax.swing.JPanel NavigationPanel1;
    private EButton PhotoSettingsMenu;
    private EButton SettingsCancelButton;
    private EButton SettingsMenu1Button1;
    private EButton SettingsMenu2Button1;
    private EButton SettingsMenu3Button;
    private EButton SettingsOKButton;
    private javax.swing.JPanel bg;
    private EPanel ePanel1;
    private EPanel ePanel2;
    private EPanel ePanel3;
    private EPanel ePanel4;
    private EPanel ePanel5;
    // End of variables declaration//GEN-END:variables
}
